### ISSUE TITLE
[BLIP-8] A BLIP to call for BLIPs

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-blips#10]
# The BLIP to call for BLIPs

Read-mes across the baseline core stack and the documentation should be updated to prompt the developer to add BLIPs whenever confused or whenever they see an opportunity for improvement across docs, code or architecture.

<John Wolpert (@humbitious)>

---
Copyright
Copyright and related rights waived via CC0-Universal.

(This template adapted from the EIP template at https://github.com/ethereum/EIPs/

**Comment by GoldenBit0** [comment]
Notes from 11/15/2021 Core Devs Session:

- @humbitious change to specify readme.md, add label 'ready for PR', someone needs to submit PR for update

**Comment by humbitious** [comment]
Changes have been made to readme and to docs here: https://docs.baseline-protocol.org/community/open-source-community/contributors#blips

Consider the work complete after pull request merged.

**Comment by GoldenBit0** [comment]
12/13/21 Core Devs:

- John made the update, pending PR

**Comment by GoldenBit0** [comment]
https://github.com/eea-oasis/baseline/pull/433/commits/67b6bd6aa693f0bca27e46c25eb3cf62fc882ce1 Merged, BLIP complete
