### ISSUE TITLE
[BLIP-] Analyst Report On Multiparty Workflow Spend and Tools

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-blips#16]
It is QED that the world is spending a ton of money in pursuit of secure multiparty workflow management. It's essential to solving many of our woes in supply chain, finance, regulation and inter-government coordination.

However, after quite a bit of searching and engaging with our known colleagues in the major analyst firms (Gartner, Forrester, IDC, Redmonk...even Grand View) there are no reports that specifically split out multiparty projects from single company projects.  You can find reports on workflow management tool sales (going to apx $5b according to one report), but you can't find anything that carves that space out specifically for projects involving two or more legally separate entities.  

It's also important to know not simply what companies and governments are spending on tools but what they are spending all up on "transformation projects" that involve multiple parties.  Services, solutions, products, home-grown, even R&D.

Proposed:  Baseline Protocol community commission a proper original research project to acquire data on this subject.

Plan: 
1) Meeting with teams like Mesh, EY, Accenture, OASIS, EEA and others who have relationships with analysts.
2) Reach-out campaign to talk with analysts to gauge methods and acquire bids.
3) Set budget based on analyst bids.
4) Engage a firm to do original research.

**Comment by GoldenBit0** [comment]
Discussions in progress with IDC (John & Sonal) and other Baseline community members getting in contact with Gartner and Forrester contacts.

**Comment by GoldenBit0** [comment]
5/2/22 Core Devs Call:

- Proposal for multi-company funded report is being drafted, will address the rise of multiparty coordination / data sharing that highlights the problems BL addresses.

**Comment by GoldenBit0** [comment]
6/13/22 Core Devs Call:

- Also being tracked in outreach team, will consolidate to one place
- A few teammates and companies are working with IDC on proposal for report.

**Comment by GoldenBit0** [comment]
6/27/22 Core Devs Call:

- In progress as part of Outreach, closing issue to track in outreach
- Sonal to send proposal to Andreas for outreach within telecoms, standards, and other communities

**Comment by GoldenBit0** [comment]
Issue being tracked in Outreach Repo here - [Research Report on Multiparty Automation #23
](https://github.com/eea-oasis/baseline-outreach/issues/23)
