### ISSUE TITLE
[BLIP-11] Repo Cleanup

### ISSUE THREAD

**Issue by Ybittan** [eea-oasis/baseline-blips#21]
# Brief and concise title for the BLIP

# Author(s)
Yoav Bittan (@Ybittan)
Keith Salzman (@Kasshern)
Sonal Patel (@GoldenBit0)

# Description
There is a need for some consolidation and cleaning of files in the repo. Certain places have redundant or repeated information that can be cleaned up to give the repo a more user friendly experience.

---

# Motivation
It will make it much easier for new members to engage with the community. Having only one source of information gives more confidence to that information being correct. Less clutter will offer contributors a better experience. 

---

**Other categories for details to include in your BLIP can be found in [additional-blip-headers.md](/.github/ISSUE_TEMPLATE/supplementary-blip-headers.md/) located in ISSUE_TEMPLATE folder**

---

# Grant Work
BLIPs that are related to an [approved grant project](https://github.com/eea-oasis/baseline-grants) require updates by the 1st of each month.
This should be provided through a comment on the issue with progress, roadblocks, and any comments.

---

Copyright and related rights waived via CC0-Universal.

**Comment by GoldenBit0** [comment]
Core Devs Update 4/4:

- Mark R created doc to track items in repo to flag as retain/archive/unsure
- Will send document to the group core devs to get input 
- Once doc is complete will start submitting PRs for moving to archival folder

**Comment by GoldenBit0** [comment]
Core Devs Update 5/2:

- Went through all files to flag for archival.
- Pending doc update.

**Comment by GoldenBit0** [comment]
Update:

- Doc updates are complete, I'm working with Oasis to sift through the remaining questions and finalize the doc redo. 
- Will connect with Core Devs at the end of the week to resolve GH/GB connection and complete proper doc update set up.

**Comment by GoldenBit0** [comment]
Core Devs Update 6/13:

- Pending PR update and resubmission 
- Link between gitbook docs / github resolved

**Comment by GoldenBit0** [comment]
Core Devs 6/27/22:

- PR merged and work complete
