### ISSUE TITLE
Create Baseline Repo Discoverability Page

### ISSUE THREAD

**Issue by fleischr** [eea-oasis/baseline-blips#33]
# Create Baseline Repo Discoverability Page - similar to dotabap.org
Author(s)
Ryan Fleischmann @fleischr

## Description

Create a simple web UI to browse and discover different github projects implementing the Baseline standard

## Motivation

As the Baseline ecosystem matures, it becomes increasingly difficult to keep all the Baseline examples inside one repo (e.g. eea-oasis/baseline). It can create issues with dependencies to any old/outdated references. Different projects within that same repo may also have conflicting dependencies that make sharing all the contributions under one repo not always the best idea. 

Other than reducing friction in maintenance of the Baseline standard repo - A web resource that organizes N-number of github repos implementing Baseline can help new and existing contributors to Baseline discover and seamlessly organize components for implementing Baseline. It could be an easier way for non-technical people to learn about projects using the standard.

Maintenance of what lands into this curated webUI list could still be governed through the maintainers group through PRs to list. Maintainers could enforce certain requirements prior to adding the repo to the UI (e.g. add a "how this implements Baseline", up to date install instructions etc).  Certain repos could also be visually marked identifying "verified" baseline implementations that have passed use of test harness and/or Maintainers & TSC in-depth review.

Creating simple, non-invasive, and discoverable ways to implement and contribute to Baseline will help our open source community and effort grow. This discoverability page ought to help in that goal.

## Proposal
Fork the WebUI and other components used by dotabap.org to create a Baseline Repo Discoverability Page. Elsewise create a similar web page area on the Baseline website

**Comment by GoldenBit0** [comment]
Core Devs 10/17/22 Meeting:

- Overall it's a good idea to have a better UI for baseline tools
- TSC / Oasis need to discuss the details here (can only open source repos be listed here? will this be a manual place to maintain alongside the BRI folders/'get baselined' site?)

**Comment by fleischr** [comment]
Unless there's someone else interested in this - I would like to withdraw this BLIP for now. I don't think I'll have time to prioritize this or work with the TSC/maintainers with it.
