### ISSUE TITLE
[BLIP-4] Baseline showcase library

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline-blips#6]
**BLIP-4 Baseline showcase library** - Development of various examples showing baselining of real-life use-cases, for the purposes of knowledge building, marketing and decision making

---

# Abstract

Current codebase lacks atomic, independent tasks that could be picked up by individual or smaller groups of core devs. Additionally, current codebase is missing examples that could be used both for marketing purposes and as a tool to help decision makers in various companies get a felling if Baseline is the right tool for their business cases. Both of these issues could be solved by defining a number of example apps that are part of a examples library (Baseline Showcase) that could then be picked up by various core devs or groups of core devs in order to enhance the process of knowledge sharing within the core devs community, increase understanding of the baseline standard and promote updates to it while at the same time developing something of value to the outside world.

# Motivation

State of the current codebase it such that it is hard for a new dev to easily fire up a development environment, run baseline stack and start exploring various components of the protocol. Large, unmerged dependencies and docker images which are outside of core dev control make it almost impossible to slice the work into smaller, atomic tasks that could be merged quickly and in a async manner. This makes the learning curve steep and reduces efficiency of any potential contribution.

Additionally, people working on Baseline promotion are missing one of the essential tools: Demos of the protocol solving some basic business use-cases. 

# Specification

Proposal consists of the following:

* Identify candidates for Baseline Showcase library. This could be the Battleship game, Excel to Excel sync or any other example use-case that shows the core features of the protocol.

* Identify team that will be in charge of defining the showcase example app structure. What are the guidelines that need to be followed when building a example app? How to properly interface or mock components defined in the standard so that we keep in line with the standard while retaining freedom to build stuff quickly and efficiently?

* Identify core devs teams and "product owners" that would be in charge of building these apps in an agile manner

# Rationale

We believe that the work on Baseline Showcase library by following the proposed steps can greatly help create a coherent core dev team that will be able to build up knowledge and generate value quickly, while at the same time keeping in mind the long-term goals of the Baseline protocols implicitly outlined in the standards document. 

# Backwards Compatibility
None

# Test Cases
None

# Reference Implementation
None

# Security Considerations

None

---
Copyright
Copyright and related rights waived via CC0-Universal.

(This template adapted from the EIP template at https://github.com/ethereum/EIPs/

**Comment by GoldenBit0** [comment]
BLIP-4 will remain a long-term, parent issue for additional BLIPS opened for specific examples.

**Comment by GoldenBit0** [comment]
1/10/22 Core Devs Session:

- Issue is a high level proposal with rationale for the development of additional examples. This work has been started by the completion of other BLIP / grant items that resulted in examples, and set the stage for efficient processes going forward.
- Issue being closed since work has been complete, content and takeaways will be used for future work and core dev organization.
