### ISSUE TITLE
[BLIP-6] Test suite for a standard-based Baseline Protocol Implementation

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline-blips#8]
**BLIP-6 Test suite for a standard-based Baseline Protocol Implementation** - Development of a monolith, dependency-free Baseline Protocol Implementation based on the standards documents, using a TDD approach

---
authors: ognjenkurtic, stefanschmidt

# Abstract

As a first step in building a standard-based, open-source Baseline Protocol Implementation (BPI), we need a set of tests running against a simple mock BPI with well-defined interfaces and component boundaries. This test suite should be implemented in such a way that it easy to run for a developer, should serve as a entry point to get to know the protocol and as a starting point to build a backlog of small, atomic tasks that can be picked up by core devs towards building a open-source 
 (BPI). 

# Motivation

At the moment, there are no open-source BPIs that can serve for core dev onboarding and as a reference for further development of the protocol. We want to start working towards resolving this by building a simple, high-level abstraction of a BPI, based on the standards and described by a set of tests documenting the core functionalities of the protocol.

# Specification

Our proposal is to finish the following before this BLIP is considered completed:

* Define the use-cases necessary to be described by tests.
* Identify main BPI components as defined in the standard and the accompanying documents (provided bellow).
* Define APIs (interfaces) between the components based on the standard and the accompanying documents.
* Select the technology based on the principle of development knowledge availability and minimal dependencies.
* Implement the tests following the TDD approach, by implementing the BPI as a monolith with mocked underlying details.
* Test harness should be able to run without internet connection.

# Rationale

In our opinion, work on this test suite and the BPI monolith would generate understanding of the standard, help refine the APIs and serve as a excellent basis to start defining further development tasks towards the goal of a standard-based, open-source Baseline Protocol Implementation.

# Backwards Compatibility
None

# Test Cases
None

# Reference Implementation

Baseline Standard Document - https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md

Baseline API and Data Model Specification - https://github.com/eea-oasis/baseline-standard/blob/main/api/baseline-api-v1.0-psd01.md

BPI Implementers Guide (Work in progress) - https://docs.google.com/document/d/1og-QseEO6B7w37h_Ik2P1pqKd8_dysRapU1PO8GeDB4/edit?usp=drivesdk

Baseline Basic Technical Walkthrough - https://www.youtube.com/watch?v=C96wepNNP4Y

# Security Considerations

None

---
Copyright
Copyright and related rights waived via CC0-Universal.

(This template adapted from the EIP template at https://github.com/ethereum/EIPs/

**Comment by ognjenkurtic** [comment]
Kickoff meeting notes - 4.11.2021
 
 First, simplest use case we want to cover:
 
 - initiator alice creates a workgroup
 - invites bob
 - agreement on the worksteps 
 - alice sends new object to bob
 - zk proof generation after succesfull workstep exection
 - storage confirmation
 - carol is not part fo the workgroup so not receiving any messages 
 
 Expanded use cases that come later:
 
 - Trudy as malicious actor
 - Trent as regulator actor 
 ...
 
 Notes:
 
 - Typescript. Node and npm as dependencies with Mocha\Jest testing framework.
 - Reference exact standard document sections from code (i.e. workstepVersion references section R220)
 - High-level architecture follows the section 6.6 BPI Transaction Lifecycle
 - Folder structure reflects the composability of the main BPI components (i.e. ICCSMClient next to concrete implementation of MockCCSMClient and EthereumClient)
 - Can be run offline
 - Mocks can be exchanged for real implementation without affecting the outcome of the tests 

 Next steps:
 
 - Next week - Mob programing session to write first tests, define components and interfaces together
 - Ognjen to prepare by looking into the standard in the context of use-case
 - Balint and Ognjen  to prepare initial testing project on a branch and a small readme

**Comment by ognjenkurtic** [comment]
Preparation session for Mob programming - meeting notes - 10.11.2021

Prepared a test project with typescript, mocha and chai. Can be found under ` BLIP-6-bpi-monolith-test-suite branch`, folder `examples\bpi-monolith-test-suite`

**Comment by kthomas** [comment]
You do know that literally all of this exists (and then some) in the Provide open source reference impl repos ;)

What if we simply monolithed them together, would that satisfy this BLIP? We can do that!

**Comment by kthomas** [comment]
@djones0 ^

**Comment by ognjenkurtic** [comment]
@kthomas The point of this BLIP is to have a number of devs building a bpi from scratch, following the standards specification, without having to rely on any external dependencies apart of the standard. It serves the purpose of knowledge building and sharing, and is a step towards a future goal of building an open-source implementation.

**Comment by humbitious** [comment]
> You do know that literally all of this exists (and then some) in the Provide open source reference impl repos ;)
> 
> What if we simply monolithed them together, would that satisfy this BLIP? We can do that!

"The answer is Provide.  What's the question?"  lol

Hey Kyle, I was thinking about starting a chicken farm, but then I figured Provide already did that, so I moved on.  ;)

**Comment by humbitious** [comment]
> > You do know that literally all of this exists (and then some) in the Provide open source reference impl repos ;)
> > What if we simply monolithed them together, would that satisfy this BLIP? We can do that!
> 
> "The answer is Provide. What's the question?" lol
> 
> Hey Kyle, I was thinking about starting a chicken farm, but then I figured Provide already did that, so I moved on. ;)

In all seriousness, Kyle, as we discussed, showing a very simple and clear from-scratch developer experience at the simplest level, able to run on localhost in a few minutes (without a dozen containers) -- and showing the videos of competent developers working in pairing fashion in real time (love these videos) on building from scratch -- will, I believe, vastly increase adoption and accessibility...leading to more developers saying, "Ok, now I get it...wish I had some real powerhouse enterprise tools to amp it up."  There's the opportunity for companies like Provide.

**Comment by ognjenkurtic** [comment]
The team got together today to split the remaining work on the BLIP. Results are here: 
https://github.com/eea-oasis/baseline/projects/2

We will be async working on these in the upcoming days, with occasional ad-hoc touchpoints.

**Comment by GoldenBit0** [comment]
Core Devs 12/13/2021: 

- Team has split up the standards document to add to monolith
- Sonal will follow up this week on timeilne for grant funds
